### ISSUE TITLE
Table separator between header and body has too many columns

### ISSUE THREAD

**Issue by ian-craig** [mysticmind/reversemarkdown-net#37] opened 2019-04-18 04:49 UTC
When converting a table, the separator between header and body (`| --- | `...) now seems to have too many columns. 

From the tests I've done, for **n** columns of content there are **2*n + 1** separator columns

Expected (and actual in v3.0.0)
```
| Fruit  | Quantity |
| --- | --- |
| Apples | 100 |
```

Actual in v3.4.0
```
| Fruit  | Quantity |
| --- | --- | --- | --- | --- |
| Apples | 100 |
```

**Comment by mysticmind** [comment] 2019-04-18 05:25
@ian-craig Thanks for reporting the issue. Looks like a regression due to the changes done to handling of headers, will fix the same.

**Comment by mysticmind** [comment] 2019-04-18 05:26
@ian-craig can you provide a test sample which you ran?

**Comment by ian-craig** [comment] 2019-04-18 05:59
Sure, just the most basic formatting will do it

```
<table>
	<tr>
		<th>Fruit</th>
		<th>Quantity</th>
	</tr>
	<tr>
		<td>Apples</td>
		<td>100</td>
	</tr>
</table>
```

**Comment by mysticmind** [comment] 2019-04-18 07:24
Fixed via commit [b3cab04](https://github.com/mysticmind/reversemarkdown-net/commit/b3cab045cb644629b5d3be6b5b5b85ea7081ca28)

**Closed by mysticmind** 2019-04-18 07:24 UTC
Labels: bug

**Comment by mysticmind** [comment] 2019-04-18 08:18
@ian-craig  v3.5.0 is published to NuGet, please check and confirm on this issue.

**Comment by ian-craig** [comment] 2019-04-18 16:24
Tested and it looks good 🙌🎉. Thanks @mysticmind
