### ISSUE TITLE
When setting config unknownTagsConverter to "bypass" an exception is thrown when converting

### ISSUE THREAD

**Issue by ahughes02** [mysticmind/reversemarkdown-net#16] opened 2018-01-03 19:19 UTC
Exception Message: An item with the same key has already been added.
Stacktrace:
```
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at ReverseMarkdown.Converters.ByPass..ctor(Converter converter)
   at ReverseMarkdown.Converter.GetDefaultConverter(String tagName)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.Div.Convert(HtmlNode node)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.Div.Convert(HtmlNode node)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.Div.Convert(HtmlNode node)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.Div.Convert(HtmlNode node)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.Div.Convert(HtmlNode node)
   at ReverseMarkdown.Converters.ConverterBase.TreatChildren(HtmlNode node)
   at ReverseMarkdown.Converters.ByPass.Convert(HtmlNode node)
   at ReverseMarkdown.Converter.Convert(String html)
```

**Comment by ahughes02** [comment] 2018-01-03 21:56
I was able to resolve this by adding `_converters.Remove(tagName);` just before `_converters.Add(tagName, converter);` in the Converter.cs Register method. Not sure if that is the correct fix but it worked for my project.

**Comment by mysticmind** [comment] 2018-01-04 12:03
@ahughes02 definitely looks like a bug, could you please provide a repro use case (including sample html) to reproduce the issue?

**Comment by ahughes02** [comment] 2018-01-04 13:25
Here is some sample HTML that causes the bug https://pastebin.com/raw/0nG6582p
This is the code I am running, except I am loading the HTML from a file. Pasting it inline works to demonstrate the bug though. I am not registering my own converter.
```var config = new ReverseMarkdown.Config("bypass", false);
var converter = new ReverseMarkdown.Converter(config);
var html = "html goes here";
var temp = converter.Convert(html);

**Comment by mysticmind** [comment] 2018-01-04 13:34
@ahughes02 I figured out the issue, will fix and make available a new version available later today.

**Comment by ahughes02** [comment] 2018-01-04 13:50
@mysticmind thanks for the quick response! This library works really great for our application and I really appreciate you making this available for everyone

**Comment by mysticmind** [comment] 2018-01-04 17:48
v1.5 published in Nuget which includes a fix for this issue

**Closed by mysticmind** 2018-01-04 17:48 UTC
Labels: bug
